version: '3'
services:
  next-starter:
    image: next-starter
    container_name: next-starter
    build:
      dockerfile: Dockerfile.dev
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.next-starter.rule=Host(`${DOMAIN:-next-starter.localhost}`)'
      - 'traefik.http.routers.next-starter.entrypoints=web'
    ports:
      - 3001:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  load-balancer:
    image: traefik:2.9
    container_name: next-starter-load-balancer
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
