version: '3'
services:
  next-starter:
    image: next-starter
    container_name: next-starter
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
